[project]
name = "tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "domain",
    "httpx>=0.28.1",
    "infrastructure",
    "pytest>=8.3.5",
    "use-case",
]

[tool.uv.sources]
domain = { workspace = true }
infrastructure = { workspace = true }
use-case = { workspace = true }
